### PR TITLE
Marketing UI - Footer Sections

### PR DESCRIPTION
**Pull request by RummanSadiq**
### **PR Type**
Enhancement, Tests

___

### **Description**
- Added multiple footer section components for the marketing UI, including `DefaultFooterSection`, `NewsLetterSignUp`, `OriginalFooter`, `PreFooterCTA`, `SitemapLinks`, `SitemapLogoSocialMedia`, and `SocialMediaIcons`.
- Implemented Storybook stories for each new footer component.
- Updated CSS variables for primary and ring colors in `globals.css`.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><details><summary>8 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>default-footer-section.tsx</strong><dd><code>Add Default Footer Section Component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/marketing-ui/footer-sections/default-footer-section.tsx

<li>Added a new <code>DefaultFooterSection</code> component.<br> <li> Included links, logo, and text elements.<br> <li> Utilized <code>MuiLayout.Container</code> for layout.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/25/files#diff-94576c12a407f11e93409d8d738e0280234f6074b6bbd59bd5e2c8637ff18bb0">+57/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>newsletter-sign-up.tsx</strong><dd><code>Add Newsletter Sign-Up Component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/marketing-ui/footer-sections/newsletter-sign-up.tsx

<li>Added <code>NewsLetterSignUp</code> component.<br> <li> Included form handling with <code>react-hook-form</code> and <code>zod</code>.<br> <li> Added address locations and newsletter sign-up form.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/25/files#diff-03a7fbbbb9592c16070325315e9d2074e8907a0c97546bf1d3f2d2404cacf429">+187/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>original-footer.tsx</strong><dd><code>Add Original Footer Component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/marketing-ui/footer-sections/original-footer.tsx

<li>Added <code>OriginalFooter</code> component.<br> <li> Included company information, social media links, and sections.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/25/files#diff-d9b01da9b6d6e3c80152ee490f6343014d6eda7c58ddfbe05fe4d40f89db7965">+135/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>prefooter-cta.tsx</strong><dd><code>Add PreFooter CTA Component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/marketing-ui/footer-sections/prefooter-cta.tsx

<li>Added <code>PreFooterCTA</code> component.<br> <li> Included call-to-action buttons and sections.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/25/files#diff-5eebc1f5b313e588b90993feef926fd67cbdcc902b55fb130914dda4e4832b16">+174/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>sitemap-links.tsx</strong><dd><code>Add Sitemap Links Component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/marketing-ui/footer-sections/sitemap-links.tsx

<li>Added <code>SitemapLinks</code> component.<br> <li> Included sitemap sections and social media links.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/25/files#diff-d751d4f48e42721eac4f3ba7f8bf32d5ff41878ca24d1298a83efa696536d47c">+140/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>sitemap_logo_social_media.tsx</strong><dd><code>Add Sitemap with Logo and Social Media Component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/marketing-ui/footer-sections/sitemap_logo_social_media.tsx

<li>Added <code>SitemapLogoSocialMedia</code> component.<br> <li> Included logo, sitemap sections, and social media links.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/25/files#diff-ffb42c353a1fb50ce39b673ab2a02ec6829e44a82abde2984ba850ca653edeb2">+114/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>social_media-icons.tsx</strong><dd><code>Add Social Media Icons Component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/marketing-ui/footer-sections/social_media-icons.tsx

<li>Added <code>SocialMediaIcons</code> component.<br> <li> Included social media links and email subscription form.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/25/files#diff-097c9176b5a6566fd6339bc5a4c3792ba9c764364189ff5264f6ab6365c42b28">+127/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>globals.css</strong><dd><code>Update CSS Variables for Colors</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/styles/globals.css

- Updated CSS variables for primary and ring colors.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/25/files#diff-dd438e7ca4da8a47a35709920a07b6fef918609c1daa40f6e9b794ddfd3e4996">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Tests
</strong></td><td><details><summary>7 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>default-footer-section.stories.tsx</strong><dd><code>Add Story for Default Footer Section</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/marketing-ui/footer-sections/stories/default-footer-section.stories.tsx

- Added Storybook story for `DefaultFooterSection`.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/25/files#diff-353188fc710c6f697b53e727a478e720599752e0742ff42478a3e7d2ed94c3b9">+16/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>newsletter-sign-up.stories.tsx</strong><dd><code>Add Story for Newsletter Sign-Up</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/marketing-ui/footer-sections/stories/newsletter-sign-up.stories.tsx

- Added Storybook story for `NewsLetterSignUp`.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/25/files#diff-3c3b51060dddba19fac4d098094c155e79e31f74fde20a89f0b5eaf1c3b95b2d">+17/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>original-footer.stories.tsx</strong><dd><code>Add Story for Original Footer</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/marketing-ui/footer-sections/stories/original-footer.stories.tsx

- Added Storybook story for `OriginalFooter`.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/25/files#diff-bc41863b8981e607bdece622a897364f7417e384f1f5e052937ed67d1e240935">+16/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pre-footer-cta.stories.tsx</strong><dd><code>Add Story for PreFooter CTA</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/marketing-ui/footer-sections/stories/pre-footer-cta.stories.tsx

- Added Storybook story for `PreFooterCTA`.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/25/files#diff-56ca9881952ac6bf886c6a02cf673f37e70a23f0d69b8a15f7b7f120028a05e1">+16/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>sitemap-links.stories.tsx</strong><dd><code>Add Story for Sitemap Links</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/marketing-ui/footer-sections/stories/sitemap-links.stories.tsx

- Added Storybook story for `SitemapLinks`.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/25/files#diff-e6ea1c4b4b6f9c4960c41350705f696bf72f7a51eb918635f5394ecff4c1874f">+16/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>sitemap_logo_social_media.stories.tsx</strong><dd><code>Add Story for Sitemap with Logo and Social Media</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/marketing-ui/footer-sections/stories/sitemap_logo_social_media.stories.tsx

- Added Storybook story for `SitemapLogoSocialMedia`.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/25/files#diff-97567efefc314c770e954cb9805fc854888dc0ced560632c88921efce4b54b48">+16/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>social_media-icons.stories.tsx</strong><dd><code>Add Story for Social Media Icons</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/marketing-ui/footer-sections/stories/social_media-icons.stories.tsx

- Added Storybook story for `SocialMediaIcons`.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/25/files#diff-b7918d8941b0a6f57fffb534890e931cbc2029542df654c2ac878c6a846f4b23">+16/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by nnennajohn — CHANGES_REQUESTED** [review]
Address PR feedback

**Comment by nnennajohn** [comment]
@RummanSadiq , I don't see a PR addressing the PR feedback

**Comment by RummanSadiq** [comment]
> @RummanSadiq , I don't see a PR addressing the PR feedback

Pushed the changes

**Comment by RummanSadiq** [comment]
> @RummanSadiq , I don't see a PR addressing the PR feedback

Pushed the changes please check it again

**Review by nnennajohn — APPROVED** [review]
Thank you.

**Pull request merged**
