### PR TITLE
refactor(sections) match create-modals, dashboard-footers, and dashbo…

### PR DESCRIPTION
**Pull request by TheOrcDev**
### **User description**
…ard-navbars with original components

___

### **PR Type**
enhancement, bug fix

___

### **Description**
- Refactored various modals to improve consistency and simplify components.
- Updated dashboard footers and navbars for better layout and styling.
- Simplified mobile menu visibility logic across multiple components.
- Added icons to dropdown buttons for better user experience.
- Fixed minor layout issues and ensured consistent styling.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><details><summary>13 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>advanced-event.tsx</strong><dd><code>Refactor Advanced Event Modal for Consistency and Simplicity</code></dd></summary>
<hr>
      
src/components/sections/application-ui/create-modals/advanced-event.tsx

<li>Removed default date value.<br> <li> Updated CSS classes for consistency.<br> <li> Replaced <code>Button</code> with <code>Input</code> for date selection.<br> <li> Simplified text color classes.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/15/files#diff-b00e73c1831f4f033d80d800b5845d3bb06a0602341f1030584559bb2dfa0b90">+26/-33</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>advanced-user.tsx</strong><dd><code>Update Advanced User Modal Layout and Avatar Upload</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/application-ui/create-modals/advanced-user.tsx

- Adjusted modal width.
- Updated avatar upload section.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/15/files#diff-e15f52059148ddf47ebcfa94d685cde2483eea2e679fd79d9f7dd8843f95e5d2">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>event.tsx</strong><dd><code>Simplify Date Selection in Event Modal</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/application-ui/create-modals/event.tsx

- Replaced `Button` with `Input` for date selection.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/15/files#diff-06d5fe0582b66cd8aeba1230a91d4d26f395e2372274c26c047cb2273581d402">+8/-7</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>product.tsx</strong><dd><code>Add Outline Variant to Discard Button in Product Modal</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/application-ui/create-modals/product.tsx

- Added `variant="outline"` to discard button.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/15/files#diff-c13c9607c7a91aaa1e18f7c32076d307c2ed4b6e52fb472b109de1fd1855303e">+4/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>default.tsx</strong><dd><code>Improve Default Dashboard Footer Layout and Tooltip Styling</code></dd></summary>
<hr>
      
src/components/sections/application-ui/dashboard-footers/default.tsx

<li>Updated footer layout to be more flexible.<br> <li> Ensured consistent background color for tooltips.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/15/files#diff-dbd6a7275682f36a284da4fb45945bf04763b8d332c7d1c7078ca19c1ad754e0">+5/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>language-selector.tsx</strong><dd><code>Standardize Tooltip Background in Footer with Language Selector</code></dd></summary>
<hr>
      
src/components/sections/application-ui/dashboard-footers/language-selector.tsx

- Ensured consistent background color for tooltips.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/15/files#diff-7538b9bfc4589fb583f5b4ac8234b009fda52ec351ad0ef1cb28938bf6c4087f">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pagination.tsx</strong><dd><code>Remove Border from Select Trigger in Pagination Footer</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/application-ui/dashboard-footers/pagination.tsx

- Removed border from `SelectTrigger`.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/15/files#diff-f2d2e36311b23ccc32535cadf330b6a4f19dd755a079eb8d7c91168e50c0bbd5">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>centered-cta-search.tsx</strong><dd><code>Simplify Mobile Menu Visibility Logic in Centered Navbar</code>&nbsp; </dd></summary>
<hr>
      
src/components/sections/application-ui/dashboard-navbars/centered-cta-search.tsx

- Simplified mobile menu visibility logic.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/15/files#diff-45399fe33b1244d8c549ecfe3df4a008c72a7bad6578875f1d10f7787184056b">+77/-77</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>cta-search.tsx</strong><dd><code>Simplify Mobile Menu Visibility Logic in Triple Navbar</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/application-ui/dashboard-navbars/cta-search.tsx

- Simplified mobile menu visibility logic.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/15/files#diff-268380eb2556007efca2439b243764e7de15e26712ae642fb685affabb82ef67">+71/-71</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>default.tsx</strong><dd><code>Adjust Search Input Width in Default Navbar</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/application-ui/dashboard-navbars/default.tsx

- Adjusted search input width.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/15/files#diff-78e3e7b2ffc98e9bd0fbf558688eccc6b759d6590b93dd1811489dcf6afb179c">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>project-dropdown.tsx</strong><dd><code>Simplify Mobile Menu Logic and Update Dropdown Items in Project </code><br><code>Dropdown Navbar</code></dd></summary>
<hr>
      
src/components/sections/application-ui/dashboard-navbars/project-dropdown.tsx

<li>Simplified mobile menu visibility logic.<br> <li> Updated dropdown menu items.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/15/files#diff-56314b1e4c83c650443e2cddff9e71104063c4dd8a9bc80f0fcf777b0586106e">+244/-246</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>project-switch-subnav.tsx</strong><dd><code>Simplify Mobile Menu Logic and Update Dropdown Items in Project Switch </code><br><code>Subnav</code></dd></summary>
<hr>
      
src/components/sections/application-ui/dashboard-navbars/project-switch-subnav.tsx

<li>Simplified mobile menu visibility logic.<br> <li> Updated dropdown menu items.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/15/files#diff-0b521b5cb61392ac7075d86a21e8df9ce434d0572241bedb780eba2c04eb51ac">+81/-140</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>search-input.tsx</strong><dd><code>Enhance Dropdown Buttons with Icons and Adjust Padding in Search Input </code><br><code>Navbar</code></dd></summary>
<hr>
      
src/components/sections/application-ui/dashboard-navbars/search-input.tsx

<li>Added <code>HiChevronDown</code> icon to dropdown buttons.<br> <li> Adjusted button padding and variants.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/15/files#diff-108f1ac71998aeceaf5fcbbd4f8cc4611282639b428f2b05f223952a26bda3e2">+28/-27</a>&nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by nnennajohn** [comment]
@TheOrcDev , please see PR review and address them. Thank you.

**Review by nnennajohn — CHANGES_REQUESTED** [review]
Please address pr review comments. Thank you.

**Comment by TheOrcDev** [comment]
Fixed. This AI Codium is awesome! Gotta use it on my projects

**Review by nnennajohn — APPROVED** [review]
Thank you.

**Pull request merged**
