### PR TITLE
refactor(application-ui) Matching UI with original components

### PR DESCRIPTION
**Pull request by TheOrcDev**
### **PR Type**
Enhancement

___

### **Description**
- Refactored user management layout and table structure by removing unused icons, updating table headers and cell contents, adjusting dropdown menu width, and reordering table columns.
- Enhanced product creation modal layout by removing `ScrollArea` import, updating dialog content and form structure, adding new input fields, and improving layout and styling.
- Enhanced user profile sidebar with additional dropdown menus for apps, notifications, and support, and improved layout and styling.
- Refactored default advanced table and pagination by removing unused pagination components, updating dropdown menu content and alignment, and improving pagination buttons and layout.
- Refactored default CRUD layout and pagination by removing unused pagination components, updating dropdown menu content and alignment, and improving pagination buttons and layout.
- Refactored project management table and pagination by removing unused pagination components, updating dropdown menu content and alignment, and improving pagination buttons and layout.
- Refactored user management table and pagination by removing unused pagination components, updating dropdown menu content and alignment, and improving pagination buttons and layout.
- Enhanced sortable rows table layout by updating dropdown menu content and alignment, and improving table cell layout and styling.
- Enhanced product management layout by removing unused pagination components, adding new icons and tooltips, updating dropdown menu content and alignment, and improving pagination buttons and layout.
- Enhanced horizontal cards layout by removing unused pagination components, adding new filter button and dropdown menu, and improving pagination buttons and layout.
- Refactored delete confirmation dialog layout by updating dialog content layout and styling, and improving form structure and button placement.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><details><summary>11 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>user-management.tsx</strong><dd><code>Refactor user management layout and table structure</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/application-ui/crud-layouts/user-management.tsx

<li>Removed unused icons.<br> <li> Updated table headers and cell contents.<br> <li> Adjusted dropdown menu width.<br> <li> Reordered table columns and modified cell content.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/39/files#diff-07f79ef8e7679006c488936785628ffed20f8d881607119aa8d304edbef910f0">+115/-360</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>product.tsx</strong><dd><code>Enhance product creation modal layout and fields</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/application-ui/create-modals/product.tsx

<li>Removed <code>ScrollArea</code> import.<br> <li> Updated dialog content and form structure.<br> <li> Added new input fields and adjusted existing ones.<br> <li> Improved layout and styling of the form.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/39/files#diff-c13c9607c7a91aaa1e18f7c32076d307c2ed4b6e52fb472b109de1fd1855303e">+200/-206</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>user-profile-sidebar.tsx</strong><dd><code>Enhance user profile sidebar with additional dropdown menus</code></dd></summary>
<hr>
      
src/components/sections/application-ui/application-shells/user-profile-sidebar.tsx

<li>Added new icons.<br> <li> Enhanced user profile sidebar with dropdown menus for apps, <br>notifications, and support.<br> <li> Improved layout and styling.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/39/files#diff-738d4e896b3a6a9ba4b25832f3e1ad7c61223ec88122fadb9a8aa8a9a886ae2d">+307/-16</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>default.tsx</strong><dd><code>Refactor default advanced table and pagination</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/application-ui/advanced-tables/default.tsx

<li>Removed unused pagination components.<br> <li> Updated dropdown menu content and alignment.<br> <li> Improved pagination buttons and layout.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/39/files#diff-102a89dc1dcb4a37c13d5f6feb4f80f25c61d46cbcbc103d8f9520b227f0fe2f">+85/-60</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>default.tsx</strong><dd><code>Refactor default CRUD layout and pagination</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/application-ui/crud-layouts/default.tsx

<li>Removed unused pagination components.<br> <li> Updated dropdown menu content and alignment.<br> <li> Improved pagination buttons and layout.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/39/files#diff-0297336be638dd3c4fa0e98dd2584234398121d655493ee9ad677d9038fd7f5a">+54/-36</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>project-management.tsx</strong><dd><code>Refactor project management table and pagination</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/application-ui/advanced-tables/project-management.tsx

<li>Removed unused pagination components.<br> <li> Updated dropdown menu content and alignment.<br> <li> Improved pagination buttons and layout.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/39/files#diff-c60affdf493cfa08a9b8f4c79cad615638cf1eaa1e491b83e588c159df8c2f9b">+53/-37</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>user-management.tsx</strong><dd><code>Refactor user management table and pagination</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/application-ui/advanced-tables/user-management.tsx

<li>Removed unused pagination components.<br> <li> Updated dropdown menu content and alignment.<br> <li> Improved pagination buttons and layout.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/39/files#diff-bfa682660b916d4ba50e5ae2145c8d7768127b353f54a0356968a61cf91c020a">+22/-27</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>sortable-rows.tsx</strong><dd><code>Enhance sortable rows table layout and dropdowns</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/application-ui/advanced-tables/sortable-rows.tsx

<li>Updated dropdown menu content and alignment.<br> <li> Improved table cell layout and styling.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/39/files#diff-19b088aa767f5f317d292fb387ab9ebe19d2c2a36141035fae7df2170991bea4">+22/-22</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>product-management.tsx</strong><dd><code>Enhance product management layout and pagination</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/application-ui/crud-layouts/product-management.tsx

<li>Removed unused pagination components.<br> <li> Added new icons and tooltips.<br> <li> Updated dropdown menu content and alignment.<br> <li> Improved pagination buttons and layout.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/39/files#diff-af2c93978375202349942d49dfe4f22f699fc60e63ba63bf7f3335c27d95a4b1">+77/-17</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>horizontal-cards.tsx</strong><dd><code>Enhance horizontal cards layout and pagination</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/application-ui/crud-layouts/horizontal-cards.tsx

<li>Removed unused pagination components.<br> <li> Added new filter button and dropdown menu.<br> <li> Improved pagination buttons and layout.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/39/files#diff-439a28e325240b69ffbf1b42a7e9a5a7f092f94eb7d3c1e4199cda47d04cd60d">+39/-29</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>input-field.tsx</strong><dd><code>Refactor delete confirmation dialog layout</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/application-ui/delete-confirm/input-field.tsx

<li>Updated dialog content layout and styling.<br> <li> Improved form structure and button placement.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/39/files#diff-2ca57a194872f738b3f9b7702c14d151529ed9150255c0499eba2edb6e86e1dc">+30/-35</a>&nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by TheOrcDev** [comment]
Nothing relevant from Codium AI. Please review the PR.

**Comment by nnennajohn** [comment]
@TheOrcDev , I see missing key reports from Codium. Please address relevant feedback.

Thank you.

**Review by nnennajohn — CHANGES_REQUESTED** [review]
@TheOrcDev , I see missing key reports from Codium. Please address relevant feedback.

Thank you.

**Comment by TheOrcDev** [comment]
> @TheOrcDev , I see missing key reports from Codium. Please address relevant feedback.
> 
> Thank you.

Both of those missing keys are not inside any loop. Not sure why Codium suggested that.

**Review by nnennajohn — APPROVED** [review]
Ok. Thank you.

**Pull request merged**
