### PR TITLE
Feature/ cart components

### PR DESCRIPTION
**Pull request by developer-mindpath**
### **PR Type**
Enhancement, Tests

___

### **Description**
- Added new shopping cart components: default, drawer, modal, sidebar, and table.
- Included form handling for voucher codes in all shopping cart components.
- Displayed order summaries with totals in all shopping cart components.
- Added Storybook stories for all new shopping cart components.
- Updated Storybook configuration to include all sections.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>main.ts</strong><dd><code>Update Storybook configuration to include all sections</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
.storybook/main.ts

- Updated story paths to include all sections.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/20/files#diff-2d9ab5214985b9a608b4cd47ed561a301cfd4c7d5352c7a94ee046d4e1f1af10">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Enhancement
</strong></td><td><details><summary>5 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>default.tsx</strong><dd><code>Add default shopping cart component with voucher form</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/e-commerce-ui/shopping-cart/default.tsx

<li>Added new shopping cart component with item listing and order summary.<br> <li> Included form handling for voucher codes.<br> <li> Displayed "People also bought" section.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/20/files#diff-61cfd1d193aa791f4cc30dab6426ca70708c70cc48ec644188d3430236330d0a">+407/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>drawer.tsx</strong><dd><code>Add shopping cart drawer component with voucher form</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/e-commerce-ui/shopping-cart/drawer.tsx

<li>Added shopping cart drawer component.<br> <li> Included form handling for voucher codes.<br> <li> Displayed order summary with totals.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/20/files#diff-53ea163711ca495e93f289072121aaab9dd5b12e255ec48fc936e702ee6a6bdd">+332/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>modal.tsx</strong><dd><code>Add shopping cart modal component with voucher form</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/e-commerce-ui/shopping-cart/modal.tsx

<li>Added shopping cart modal component.<br> <li> Included form handling for voucher codes.<br> <li> Displayed order summary with totals.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/20/files#diff-c5a05b397aa7c30e11919c27c898923b3d0b0875c86cd18d074f363c1aebb720">+318/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>sidebar.tsx</strong><dd><code>Add shopping cart sidebar component with voucher form</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/e-commerce-ui/shopping-cart/sidebar.tsx

<li>Added shopping cart sidebar component.<br> <li> Included form handling for voucher codes.<br> <li> Displayed order summary with totals.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/20/files#diff-cae817ba42fe3afa9b72f25c618c00fc71a093b45049ea7ce27b7bac15478016">+362/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>table.tsx</strong><dd><code>Add shopping cart table component with order summary</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/e-commerce-ui/shopping-cart/table.tsx

<li>Added shopping cart table component.<br> <li> Displayed order summary with totals.<br>

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/20/files#diff-617a7066c6ced543695221640b317d9f248d17986dbd4099b5c44d448fa30d8d">+234/-0</a>&nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Tests
</strong></td><td><details><summary>5 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>default.stories.tsx</strong><dd><code>Add Storybook story for default shopping cart component</code>&nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/e-commerce-ui/shopping-cart/stories/default.stories.tsx

- Added Storybook story for default shopping cart component.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/20/files#diff-34105de83645e45c61d5e1fb958c495120a54532a9d0fc0f5c65e4a4fcfed9fd">+16/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>drawer.stories.tsx</strong><dd><code>Add Storybook story for shopping cart drawer component</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/e-commerce-ui/shopping-cart/stories/drawer.stories.tsx

- Added Storybook story for shopping cart drawer component.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/20/files#diff-e5f9c21289124fdcaaf4e54478407a8fbcc947aa09bbad015bc8d3a5eaa9de29">+16/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>modal.stories.tsx</strong><dd><code>Add Storybook story for shopping cart modal component</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/e-commerce-ui/shopping-cart/stories/modal.stories.tsx

- Added Storybook story for shopping cart modal component.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/20/files#diff-4eac9d954b8b5dc634089e43ef19cb162e55663dbdd8d0a2d7e6eda929cc0dd1">+16/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>sidebar.stories.tsx</strong><dd><code>Add Storybook story for shopping cart sidebar component</code>&nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/e-commerce-ui/shopping-cart/stories/sidebar.stories.tsx

- Added Storybook story for shopping cart sidebar component.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/20/files#diff-0c3e272e2f8a363fc18ae711a0abf4967b8dfaeaff684ca4c1c29564580a1322">+16/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>table.stories.tsx</strong><dd><code>Add Storybook story for shopping cart table component</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
src/components/sections/e-commerce-ui/shopping-cart/stories/table.stories.tsx

- Added Storybook story for shopping cart table component.

</details>
    

  </td>
  <td><a href="https://github.com/modernui-io/modernuiweb/pull/20/files#diff-3703bc108062d670243dc458752bb028f636924912c562c62d64035dfd513eda">+16/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by nnennajohn — CHANGES_REQUESTED** [review]
Please address pr comments.

**Comment by developer-mindpath** [comment]
> Please address pr comments.

hey, i have address all the solvable comment liske map and unique keys. Please check.

**Comment by developer-mindpath** [comment]
> Please address pr comments.

hey, i have addressed the fixable comments and added uniques ids and maps.

**Review by nnennajohn — APPROVED** [review]
Thank you

**Pull request merged**
